### ISSUE TITLE
add instructions for building image and loading into cluster locally

### ISSUE THREAD

**Issue by michelleN** [spinkube/documentation#123]
https://www.spinkube.dev/docs/spin-operator/tutorials/running-locally/#running-spin-operator

Our current running locally guide instructs folks to use `make run` to run the operator locally. That's great for inner loop development. We probably want to add guidance somewhere on that page on how to build and deploy the spin operator locally as well. That involves building the spin-operator dev image (`make docker-build`), load into k3d cluster (`k3d images load -c <cluster_name> <image>`) , and deploy (`make deploy`)

**Comment by ThorstenHans** [comment]
IIRC that's intentional to address inner loop dev. However there is the "Running on a Cluster guide" at https://www.spinkube.dev/docs/spin-operator/tutorials/running-on-a-cluster/ and a dedicated article on how to build and share a custom Spin Operator image at https://www.spinkube.dev/docs/spin-operator/tutorials/share-operator-image/

I'll look into that one and try to make those guides more self-explaining and link the "Share Spin Operator Image" page from both guides.

WDYT @michelleN

**Comment by bacongobbler** [comment]
FYI, new locations are here:

- https://www.spinkube.dev/docs/contrib/running-locally/
- https://www.spinkube.dev/docs/contrib/running-on-a-cluster/
- https://www.spinkube.dev/docs/contrib/share-operator-image/
